# Generated by Django 3.0.6 on 2020-06-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='custom',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
